const ROLES = {
  CUSTOMER: "customer",
  OPERATOR: "operator",
  ADMIN: "admin",
};

const MACHINE_STATUS = {
  ACTIVE: "ACTIVE",
  MAINTENANCE: "MAINTENANCE",
  INACTIVE: "INACTIVE",
};

const CONNECTIVITY = {
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
};

const LOCKER_SIZES = ["small", "medium", "large"];

// Normal states + failure states from the spec
const LOCKER_STATUS = {
  AVAILABLE: "AVAILABLE",
  RESERVED: "RESERVED",
  OCCUPIED: "OCCUPIED",
  EXPIRED: "EXPIRED",
  HOLDING: "HOLDING",
  RELEASED: "RELEASED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  OPENING_FAILED: "OPENING_FAILED",
  SENSOR_TIMEOUT: "SENSOR_TIMEOUT",
  MACHINE_OFFLINE: "MACHINE_OFFLINE",
  MAINTENANCE: "MAINTENANCE",
};

const DOOR_STATE = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  UNKNOWN: "UNKNOWN",
};
const RENTAL_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  OPENING_FAILED: "OPENING_FAILED",
};
const PAYMENT_TYPE = {
  RENTAL: "RENTAL",
  FINE: "FINE", // used later for expiry fines
};

const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
  REFUND_REQUIRED: "REFUND_REQUIRED",
};
const OTP_PURPOSE = {
  LOCKER_ACCESS: "LOCKER_ACCESS",
};

const OTP_STATUS = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  CONSUMED: "CONSUMED",
  INVALIDATED: "INVALIDATED",
};
const COMMAND_STATUS = {
  PENDING: "PENDING",     // queued, not yet delivered
  SENT: "SENT",           // delivered to the machine
  RELEASED: "RELEASED",   // device says the lock was actuated
  CONFIRMED: "CONFIRMED", // door sensor confirmed the door is open
  COMPLETED: "COMPLETED", // door closed again
  FAILED: "FAILED",       // device reported failure
  TIMEOUT: "TIMEOUT",     // delivered but no acknowledgement
  ABANDONED: "ABANDONED", // never opened; no fault
};

const COMMAND_IN_FLIGHT = [
  COMMAND_STATUS.PENDING,
  COMMAND_STATUS.SENT,
  COMMAND_STATUS.RELEASED,
  COMMAND_STATUS.CONFIRMED,
];

const ACCESS_PURPOSE = {
  DEPOSIT: "DEPOSIT",
  RETRIEVE: "RETRIEVE",
};
module.exports = {
  ROLES,
  MACHINE_STATUS,
  CONNECTIVITY,
  LOCKER_SIZES,
  LOCKER_STATUS,
  DOOR_STATE,
  RENTAL_STATUS,
  PAYMENT_TYPE,
  PAYMENT_STATUS,
  OTP_PURPOSE,
  OTP_STATUS,
  COMMAND_STATUS,
  COMMAND_IN_FLIGHT,
  ACCESS_PURPOSE,
};