const ROLES = {
  CUSTOMER: "customer",
  OPERATOR: "operator",
  ADMIN: "admin",
};

const MACHINE_STATUS = {
  ACTIVE: "ACTIVE",
  MAINTENANCE: "MAINTENANCE",
  INACTIVE: "INACTIVE",
};

const CONNECTIVITY = {
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
};

const LOCKER_SIZES = ["small", "medium", "large"];

// Normal states + failure states from the spec
const LOCKER_STATUS = {
  AVAILABLE: "AVAILABLE",
  RESERVED: "RESERVED",
  OCCUPIED: "OCCUPIED",
  EXPIRED: "EXPIRED",
  HOLDING: "HOLDING",
  RELEASED: "RELEASED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  OPENING_FAILED: "OPENING_FAILED",
  SENSOR_TIMEOUT: "SENSOR_TIMEOUT",
  MACHINE_OFFLINE: "MACHINE_OFFLINE",
  MAINTENANCE: "MAINTENANCE",
};

const DOOR_STATE = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  UNKNOWN: "UNKNOWN",
};
const RENTAL_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  OPENING_FAILED: "OPENING_FAILED",
};
module.exports = {
  ROLES,
  MACHINE_STATUS,
  CONNECTIVITY,
  LOCKER_SIZES,
  LOCKER_STATUS,
  DOOR_STATE,
  RENTAL_STATUS,
};